export const GET_INFORMATION_CODES_REQUEST = 'common/GET_INFORMATION_CODES_REQUEST';
export const GET_INFORMATION_CODES_SUCCESS = 'common/GET_INFORMATION_CODES_SUCCESS';
export const GET_INFORMATION_CODES_FAILURE = 'common/GET_INFORMATION_CODES_FAILURE';

export const GET_INFORMATION_FIELDS_REQUEST = 'common/GET_INFORMATION_FIELDS_REQUEST';
export const GET_INFORMATION_FIELDS_SUCCESS = 'common/GET_INFORMATION_FIELDS_SUCCESS';
export const GET_INFORMATION_FIELDS_FAILURE = 'common/GET_INFORMATION_FIELDS_FAILURE';

export const GET_INFORMATION_TYPES_REQUEST = 'common/GET_INFORMATION_TYPES_REQUEST';
export const GET_INFORMATION_TYPES_SUCCESS = 'common/GET_INFORMATION_TYPES_SUCCESS';
export const GET_INFORMATION_TYPES_FAILURE = 'common/GET_INFORMATION_TYPES_FAILURE';
