export const GET_ALL_RECORDS_REQUEST = 'records/GET_ALL_RECORDS_REQUEST';
export const GET_ALL_RECORDS_SUCCESS = 'records/GET_ALL_RECORDS_SUCCESS';
export const GET_ALL_RECORDS_FAILURE = 'records/GET_ALL_RECORDS_FAILURE';

export const CREATE_RECORD_REQUEST = 'records/CREATE_RECORD_REQUEST';
export const CREATE_RECORD_SUCCESS = 'records/CREATE_RECORD_SUCCESS';
export const CREATE_RECORD_FAILURE = 'records/CREATE_RECORD_FAILURE';
