export const CREATE_ORDER_REQUEST = 'orders/CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'orders/CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'orders/CREATE_ORDER_FAILURE';

export const GET_ALL_ORDERS_REQUEST = 'orders/GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'orders/GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILURE = 'orders/GET_ALL_ORDERS_FAILURE';

